openapi: 3.0.3
info:
  title: 소상톡톡 관리자 API
  version: 0.0.1
servers:
  - url: https://sotalk.example.com/api/admin/v1
tags:
  - name: 회원가입
  - name: 로그인
  - name: 게시글 관리
  - name: 컨텐츠 관리

paths:
  /board/best:
    get:
      tags:
        - 컨텐츠 관리
      summary: 인기글 목록
      parameters:
        - name: pin
          in: query
          description: 고정게시글 여부
          required: false
          schema:
            type: boolean
            example: false
        - name: page
          in: query
          description: 현재 페이지
          required: true
          schema:
            type: integer
        - name: size
          in: query
          description: 페이지 당 표시 갯수
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              examples:
                empty:
                  value:
                    totalCount: 0
                    bestSize: 5
                    contents: [ ]
                two:
                  value:
                    totalCount: 2
                    bestSize: 5
                    contents:
                      - boardId: 1
                        rank: 0
                        title: "사업하는거 너무 힘드네요"
                        boardTypeName: "소상톡톡"
                        likesCount: 45
                        viewCount: 1251
                        commentsCount: 189
                        claimCount: 0
                        createdAt: "2024-11-19 18:45:00"
                        nickname: "익명의소통"
                        hidden: false
                        pin: true
                      - boardId: 2
                        rank: 1
                        title: "장사라는거 어떻게 시작하죠?"
                        boardTypeName: "소상톡톡"
                        likesCount: 43
                        viewCount: 800
                        commentsCount: 21
                        claimCount: 0
                        createdAt: "2024-11-19 18:45:00"
                        nickname: "익명의소통"
                        hidden: false
                        pin: false
                many:
                  value:
                    totalCount: 5
                    bestSize: 5
                    contents:
                      - boardId: 1
                        rank: 0
                        title: "사업하는거 너무 힘드네요"
                        boardTypeName: "소상톡톡"
                        likesCount: 45
                        viewCount: 1251
                        commentsCount: 189
                        claimCount: 0
                        createdAt: "2024-11-19 18:45:00"
                        nickname: "익명의소통"
                        hidden: false
                        pin: true
                      - boardId: 2
                        rank: 1
                        title: "장사라는거 어떻게 시작하죠?"
                        boardTypeName: "소상톡톡"
                        likesCount: 43
                        viewCount: 800
                        commentsCount: 21
                        claimCount: 0
                        createdAt: "2024-11-19 18:45:00"
                        nickname: "익명의소통"
                        hidden: false
                        pin: false
                      - boardId: 3
                        rank: 2
                        title: "사업자 대출 진행 방법"
                        boardTypeName: "사업톡톡"
                        likesCount: 20
                        viewCount: 502
                        commentsCount: 13
                        claimCount: 1
                        createdAt: "2024-11-19 18:45:00"
                        nickname: "익명의소통"
                        hidden: false
                        pin: false
                      - boardId: 4
                        rank: 3
                        title: "사업하는거 너무 힘드네요"
                        boardTypeName: "소상톡톡"
                        likesCount: 15
                        viewCount: 501
                        commentsCount: 11
                        claimCount: 2
                        createdAt: "2024-11-19 18:45:00"
                        nickname: "익명의소통"
                        hidden: false
                        pin: false
                      - boardId: 5
                        rank: 4
                        title: "사업하는거 너무 힘드네요"
                        boardTypeName: "소상톡톡"
                        likesCount: 5
                        viewCount: 51
                        commentsCount: 5
                        claimCount: 0
                        createdAt: "2024-11-19 18:45:00"
                        nickname: "익명의소통"
                        hidden: false
                        pin: false

  /board/best/size:
    get:
      tags:
        - 컨텐츠 관리
      summary: 인기글 개수 설정 목록
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example:
                  bestConfigs:
                    - bestSize: 3
                      active: false
                    - bestSize: 5
                      active: false
                    - bestSize: 10
                      active: true
                    - bestSize: 15
                      active: false
                    - bestSize: 20
                      active: false
    post:
      tags:
        - 컨텐츠 관리
      summary: 인기글 개수 설정
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bestSize:
                  type: integer
                  example: 10
      responses:
        200:
          $ref: '#/components/responses/OK'

  /board/{boardId}/pin:
    post:
      tags:
        - 컨텐츠 관리
      summary: 고정 등록
      parameters:
        - name: boardId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          $ref: '#/components/responses/OK'
    delete:
      tags:
        - 컨텐츠 관리
      summary: 고정 해제
      parameters:
        - name: boardId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          $ref: '#/components/responses/OK'

  /event:
    get:
      tags:
        - 컨텐츠 관리
      summary: 베너/이벤트 목록
      parameters:
        - name: active
          in: query
          description: 사용 여부
          required: false
          schema:
            type: boolean
            example: false
        - name: page
          in: query
          description: 현재 페이지
          required: true
          schema:
            type: integer
        - name: size
          in: query
          description: 페이지 당 표시 갯수
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              examples:
                empty:
                  value:
                    totalCount: 0
                    contents: [ ]
                two:
                  value:
                    totalCount: 2
                    contents:
                      - eventId: 1
                        title: "새로워진 업데이트 내용"
                        eventTypeName: "팝업"
                        startAt: "2024-11-19 12:00:00"
                        endAt: "2024-11-25 22:00:00"
                        duration: 72
                        screenTypeName: "게시판(홈)"
                        active: true
                      - eventId: 2
                        title: "소톡은 처음이신가요?"
                        eventTypeName: "롤링배너"
                        startAt: "2024-11-19 12:00:00"
                        endAt: "2024-11-19 17:00:00"
                        duration: 3
                        screenTypeName: "마이페이지"
                        active: false
                many:
                  value:
                    totalCount: 5
                    contents:
                      - eventId: 1
                        title: "새로워진 업데이트 내용"
                        eventTypeName: "팝업"
                        startAt: "2024-11-19 12:00:00"
                        endAt: "2024-11-25 22:00:00"
                        duration: 72
                        screenTypeName: "게시판(홈)"
                        active: true
                      - eventId: 2
                        title: "소톡은 처음이신가요?"
                        eventTypeName: "롤링배너"
                        startAt: "2024-11-19 12:00:00"
                        endAt: "2024-11-19 17:00:00"
                        duration: 3
                        screenTypeName: "마이페이지"
                        active: false
                      - eventId: 3
                        title: "소톡은 처음이신가요?"
                        eventTypeName: "롤링배너"
                        startAt: "2024-11-19 12:00:00"
                        endAt: "2024-11-25 22:00:00"
                        duration: 3
                        screenTypeName: "게시판(홈)"
                        active: false
                      - eventId: 4
                        title: "신규 생성된 멤버십제도 안내"
                        eventTypeName: "롤링배너"
                        startAt: "2024-11-19 12:00:00"
                        endAt: "2024-11-19 17:00:00"
                        duration: 3
                        screenTypeName: "게시판(홈)"
                        active: false
                      - eventId: 5
                        title: "신고 제재 관련 안내문"
                        eventTypeName: "팝업"
                        startAt: "2024-11-19 12:00:00"
                        endAt: "2024-11-19 17:00:00"
                        duration: 3
                        screenTypeName: "메세지 목록"
                        active: false
    post:
      tags:
        - 컨텐츠 관리
      summary: 베너/이벤트 등록
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "소톡은 처음이지?"
                screenType:
                  $ref: '#/components/schemas/ScreenType'
                eventType:
                  $ref: '#/components/schemas/EventType'
                always:
                  type: boolean
                  example: false
                startAt:
                  type: string
                  example: "2024-11-19 12:00:00"
                endAt:
                  type: string
                  example: "2024-11-20 23:59:59"
                attachments:
                  type: array
                  items:
                    type: string
                    format: binary
                active:
                  type: boolean
                  example: true
                content:
                  type: string
                  example: 처음 이용하는 선생님들을 위해 소톡 앱소개와 이용법을 알려줄게!
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventId:
                    type: integer
                    example: 1

components:
  schemas:
    ScreenType:
      type: string
      enum:
        - HOME
        - MESSAGE
        - MY_PAGE
        - REGISTRATION
    EventType:
      type: string
      enum:
        - ROLLING
        - POPUP
        - GUIDE
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
          required:
            - code
            - message

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  responses:
    OK:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
    Unauthorized:
      description: 액세스 토큰이 비어 있거나 유효하지 않은 경우
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            value:
              code: 401
              message: unauthorized
    Forbidden:
      description: 권한이 없는 경우
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            value:
              code: 403
              message: forbidden